image: node:latest

variables:
  PROJECT: imparsable

before_script:
  - echo "$CI_JOB_TOKEN"
  - npm set registry https://npm.xena.rocks
  - npm install

cache:
  paths:
    - node_modules/

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - npm run build
    - npm run test

publish:
  stage: deploy
  script:
    - npm run build
    - npm version --no-git-tag-version $CI_COMMIT_REF_NAME
    - npm publish
  only:
    - tags